name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  docker_push:
    runs-on: ubuntu-latest
    name: Build the bumper image, push to Docker Hub
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Bump version and push tag
        id: tagging
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ORG_REPO_TAG }}
          DEFAULT_BUMP: patch
          WITH_V: "true"
          INITIAL_VERSION: 1.0.0

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: sionsmith/strimzi-connect-all-in-one
          tags: ${{ steps.tagging.outputs.new_tag }}